# Original Dockerfile content provided by the instance
{{ dockerfile_content }}

# Copy helper script
COPY {{ script_name }} /usr/local/bin/
RUN chmod +x /usr/local/bin/{{ script_name }}

# Normalize CRLF -> LF to fix /bin/bash^M issue
RUN find /usr/local/bin /src /testcase /workspace -type f -exec sed -i 's/\r$//' {} + || true


# Create testcase directory (standard practice)
RUN mkdir -p /testcase

# Environment variables
ENV SANITIZER="{{ sanitizer }}"
ENV FUZZING_ENGINE=libfuzzer
ENV FUZZING_LANGUAGE="{{ lang or 'c++' }}"
ENV PROJECT_NAME="{{ project_name }}"
ENV ARCHITECTURE=x86_64
ENV CFLAGS="-w -Wno-yacc -Wno-incompatible-pointer-types"
ENV CXXFLAGS="-w -Wno-yacc -Wno-incompatible-pointer-types"

RUN apt-get update && apt-get install -y clang build-essential pip
ENV CC=clang
ENV CXX=clang++


# ENV CFLAGS="-w -Wno-yacc -Wno-incompatible-pointer-types -fsanitize=address -fno-omit-frame-pointer -g"
# ENV CXXFLAGS="-w -Wno-yacc -Wno-incompatible-pointer-types -fsanitize=address -fno-omit-frame-pointer -g"
# ENV LDFLAGS="-fsanitize=address"

# Workspace directory
WORKDIR {{ work_dir }}